<?php
// $Id: xoops_version.php,v 1.12 2006/09/02 09:00:52 mithyt2 Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name'] = _MI_MATCH_NAME;
$modversion['version'] = 3.01;
$modversion['versionstatus'] = "Full";
$modversion['description'] = _MI_MATCH_DESC;
$modversion['credits'] = "The XOOPS Project";
$modversion['help'] = "team.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['author'] = "Mithrandir";
$modversion['image'] = "images/team_slogo.png";
$modversion['dirname'] = "team";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "team_availability";
$modversion['tables'][1] = "team_layout"; //Move to module config
$modversion['tables'][2] = "team_ladders"; //No class
$modversion['tables'][3] = "team_lineups_positions";
$modversion['tables'][4] = "team_mappool";
$modversion['tables'][5] = "team_matches";
$modversion['tables'][6] = "team_matchmaps";
$modversion['tables'][7] = "team_positions"; //No class
$modversion['tables'][8] = "team_rank"; //No class
$modversion['tables'][9] = "team_server"; //No class
$modversion['tables'][10] = "team_sides"; //No class
$modversion['tables'][11] = "team_sizes"; //No class
$modversion['tables'][12] = "team_skills"; //No class
$modversion['tables'][13] = "team_status"; //No class
$modversion['tables'][14] = "team_tactics";
$modversion['tables'][15] = "team_tactics_positions";
$modversion['tables'][16] = "team_team";
$modversion['tables'][17] = "team_teamladders"; //No class
$modversion['tables'][18] = "team_teammaps"; //No class
$modversion['tables'][19] = "team_teampositions"; //No class
$modversion['tables'][20] = "team_teamservers"; //No class
$modversion['tables'][21] = "team_teamstatus"; //No class
$modversion['tables'][22] = "team_teamsides"; //No class
$modversion['tables'][23] = "team_teamsizes"; //No class
$modversion['tables'][24] = "team_teamrank"; //No class


// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['onUpdate'] = "include/update.php";

// Blocks
$modversion['blocks'][1]['file'] = "availability.php";
$modversion['blocks'][1]['name'] = _MI_MATCH_BNAME1;
$modversion['blocks'][1]['description'] = "Shows personal availability";
$modversion['blocks'][1]['show_func'] = "sh_availability";
$modversion['blocks'][2]['file'] = "navmenu.php";
$modversion['blocks'][2]['name'] = _MI_MATCH_BNAME2;
$modversion['blocks'][2]['description'] = "Shows Navigation Menu";
$modversion['blocks'][2]['show_func'] = "sh_navmenu";

// Templates
$modversion['templates'][1]['file'] = 'team_userprofile.html';
$modversion['templates'][1]['description'] = 'Player Profile';
$modversion['templates'][2]['file'] = 'team_matchdetails.html';
$modversion['templates'][2]['description'] = 'Match Details';
$modversion['templates'][3]['file'] = 'team_matchlist.html';
$modversion['templates'][3]['description'] = 'List of Matches';
$modversion['templates'][4]['file'] = 'team_availability.html';
$modversion['templates'][4]['description'] = 'Match Availability';
$modversion['templates'][5]['file'] = 'team_roster.html';
$modversion['templates'][5]['description'] = 'Team Roster';
$modversion['templates'][6]['file'] = 'team_select.html';
$modversion['templates'][6]['description'] = 'Selection Template';
$modversion['templates'][7]['file'] = 'team_teamadmin.html';
$modversion['templates'][7]['description'] = 'Team Administration';
$modversion['templates'][8]['file'] = 'team_avstats.html';
$modversion['templates'][8]['description'] = 'Availability Statistics';
$modversion['templates'][9]['file'] = 'team_positions.html';
$modversion['templates'][9]['description'] = 'Position Tables';
$modversion['templates'][10]['file'] = 'team_tactics_list.html';
$modversion['templates'][10]['description'] = 'Tactics list table';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_MATCH_SMNAME2;
$modversion['sub'][1]['url'] = "index.php";
$modversion['sub'][2]['name'] = _MI_MATCH_SMNAME3;
$modversion['sub'][2]['url'] = "roster.php";
$modversion['sub'][3]['name'] = _MI_MATCH_SMNAME4;
$modversion['sub'][3]['url'] = "tactics.php";

//Preferences
/*
$modversion['config'][1]['name'] = 'selected_sections';
$modversion['config'][1]['title'] = '_MI_TEAM_SECTIONS';
$modversion['config'][1]['description'] = '_MI_TEAM_SECTIONSDESC';
$modversion['config'][1]['formtype'] = 'select_multi';
$modversion['config'][1]['valuetype'] = 'array';
$modversion['config'][1]['default'] = array('Tactics', 'Matches', 'Availability', 'Stats', 'Player Profiles');
$modversion['config'][1]['options'] = array(
                                    'Tactics' => 1,
                                    'Matches' => 2,
                                    'Availability' => 3,
                                    'Stats' => 4,
                                    'Player Profiles' => 5);
*/
//Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'team_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'match';
$modversion['notification']['category'][1]['title'] = _MI_TEAM_MATCH_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_TEAM_MATCH_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('matchdetails.php', 'availability.php' );
$modversion['notification']['category'][1]['item_name'] = 'mid';

$modversion['notification']['category'][2]['name'] = 'team';
$modversion['notification']['category'][2]['title'] = _MI_TEAM_MATCH_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_TEAM_MATCH_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = 'index.php';
$modversion['notification']['category'][2]['item_name'] = 'teamid';

$modversion['notification']['event'][1]['name'] = 'new_match';
$modversion['notification']['event'][1]['category'] = 'team';
$modversion['notification']['event'][1]['title'] = _MI_TEAM_NEWMATCH_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_TEAM_NEWMATCH_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_TEAM_NEWMATCH_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'team_newmatch_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_TEAM_NEWMATCH_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'new_lineup';
$modversion['notification']['event'][2]['category'] = 'match';
$modversion['notification']['event'][2]['title'] = _MI_TEAM_NEWLINEUP_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_TEAM_NEWLINEUP_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_TEAM_NEWLINEUP_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'team_newlineup_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_TEAM_NEWLINEUP_NOTIFYSBJ;
?>